spring:
  application:
    name: zipkin
  profiles:
      active: local
  rabbitmq:
    addresses: 192.168.14.97
    port: 5672
    username: guest
    password: guest

server:
  port: 9411

---
###################  开发环境的profile  ###################
spring:
  profiles: local


logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG