spring:
  application:
    name: zipkin
  profiles:
      active: local
  rabbitmq:
    addresses: 192.168.14.97
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://192.168.14.98:3333/zipkin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    continue-on-error: true
    initialize: true
    schema: classpath:/mysql.sql

zipkin:
  storage:
    StorageComponent: mysql
    #type: mysql

server:
  port: 9411

---
###################  开发环境的profile  ###################
spring:
  profiles: local


logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG