spring:
  application:
    name: example-service
  profiles:
      active: local

server:
  port: 10004

---
###################  开发环境的profile  ###################
spring:
  profiles: local
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  instance:
      #hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG